=== AdjustmentBeaver/szoftlab/Assets/levels/level.dtd
<!ELEMENT level (nodes,trains)>
<!ELEMENT nodes (node*)>
<!ELEMENT node (position, neighbours)>
<!ATTLIST node type CDATA #REQUIRED>
<!ATTLIST node name CDATA #REQUIRED>
<!ATTLIST node color CDATA #IMPLIED>
<!ELEMENT position EMPTY>
<!ATTLIST position x CDATA #REQUIRED>
<!ATTLIST position y CDATA #REQUIRED>
<!ELEMENT neighbours (neighbour*)>
<!ELEMENT neighbour EMPTY>
<!ATTLIST neighbour name CDATA #REQUIRED>
<!ELEMENT trains (train*)>
<!ELEMENT train (trainPart*)>
<!ATTLIST train start_node CDATA #REQUIRED>
<!ATTLIST train start_time CDATA #REQUIRED>
<!ELEMENT trainPart EMPTY>
<!ATTLIST trainPart type CDATA #REQUIRED>
<!ATTLIST trainPart speed CDATA #IMPLIED>
<!ATTLIST trainPart color CDATA #IMPLIED>

=== AdjustmentBeaver/szoftlab/Code/xmlparser/data/palya.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="sin1">
            <position x="0" y="1"/>
            <neighbours>
                <neighbour name="sin2"/>
            </neighbours>
        </node>
        <node type="node" name="sin2">
            <position x="1" y="1"/>
            <neighbours>
                <neighbour name="sin1"/>
                <neighbour name="valto"/>
            </neighbours>
        </node>
        <node type="switch" name="valto">
            <position x="2" y="1"/>
            <neighbours>
                <neighbour name="sin2"/>
                <neighbour name="sin3"/>
                <neighbour name="sin4"/>
            </neighbours>
        </node>
        <node type="node" name="sin3">
            <position x="2" y="2"/>
            <neighbours>
                <neighbour name="valto"/>
            </neighbours>
        </node>
        <node type="node" name="sin4">
            <position x="2" y="0"/>
            <neighbours>
                <neighbour name="valto"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="sin1" start_time="0">
            <trainPart type="engine" speed="1"/>
            <trainPart type="cart" color="blue"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Assets/levels/cvtest.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="n1">
            <position x="20" y="20"/>
            <neighbours>
                <neighbour name="sw1"/>
            </neighbours>
        </node>
        <node type="switch" name="sw1">
            <position x="120" y="20"/>
            <neighbours>
                <neighbour name="n1"/>
                <neighbour name="n2"/>
                <neighbour name="t1"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="t1">
            <position x="120" y="120"/>
            <neighbours>
                <neighbour name="sw1"/>
            </neighbours>
        </node>
        <node type="node" name="n2">
            <position x="220" y="20"/>
            <neighbours>
                <neighbour name="sw1"/>
                <neighbour name="l1"/>
            </neighbours>
        </node>
        <node type="loaderStation" name="l1" color="blue">
            <position x="220" y="120"/>
            <neighbours>
                <neighbour name="n2"/>
                <neighbour name="n3"/>
            </neighbours>
        </node>
        <node type="node" name="n3">
            <position x="320" y="120"/>
            <neighbours>
                <neighbour name="l1"/>
                <neighbour name="s1"/>
            </neighbours>
        </node>
        <node type="station" name="s1" color="blue">
            <position x="320" y="220"/>
            <neighbours>
                <neighbour name="n3"/>
                <neighbour name="t2"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="t2">
            <position x="220" y="220"/>
            <neighbours>
                <neighbour name="s1"/>
            </neighbours>
        </node>

        <node type="specialPlace" name="t3">
            <position x="20" y="120"/>
            <neighbours>
                <neighbour name="n4"/>
            </neighbours>
        </node>
        <node type="node" name="n4">
            <position x="20" y="220"/>
            <neighbours>
                <neighbour name="t3"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="n1" start_time="0">
            <trainPart type="engine" speed="2"/>
            <trainPart type="cart" color="blue"/>
            <trainPart type="coalWagon"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Code/szoftlab/levels/hosszu.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="node1">
            <position x="0" y="0"/>
            <neighbours>
                <neighbour name="switch1"/>
            </neighbours>
        </node>
        <node type="switch" name="switch1">
            <position x="1" y="0"/>
            <neighbours>
                <neighbour name="node1"/>
                <neighbour name="node2"/>
                <neighbour name="node3"/>
            </neighbours>
        </node>
        <node type="node" name="node2">
            <position x="2" y="0"/>
            <neighbours>
                <neighbour name="switch1"/>
                <neighbour name="node4"/>
            </neighbours>
        </node>
        <node type="node" name="node3">
            <position x="1" y="1"/>
            <neighbours>
                <neighbour name="switch1"/>
            </neighbours>
        </node>
        <node type="node" name="node4">
            <position x="3" y="0"/>
            <neighbours>
                <neighbour name="node2"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="node1" start_time="0">
            <trainPart type="engine"/>
            <trainPart type="cart"/>
            <trainPart type="coalWagon"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Code/szoftlab/levels/cvtest.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="n1">
            <position x="20" y="20"/>
            <neighbours>
                <neighbour name="sw"/>
            </neighbours>
        </node>
        <node type="switch" name="sw">
            <position x="100" y="20"/>
            <neighbours>
                <neighbour name="n2"/>
                <neighbour name="n1"/>
                <neighbour name="n3"/>
            </neighbours>
        </node>
        <node type="node" name="n2">
            <position x="200" y="20"/>
            <neighbours>
                <neighbour name="sw"/>
                <neighbour name="s1"/>
            </neighbours>
        </node>
        <node type="node" name="n3">
            <position x="100" y="100"/>
            <neighbours>
                <neighbour name="sw"/>
                <neighbour name="s3"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="s1">
            <position x="300" y="20"/>
            <neighbours>
                <neighbour name="n2"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="s2">
            <position x="500" y="450"/>
            <neighbours>
                <neighbour name="s4"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="s3">
            <position x="100" y="200"/>
            <neighbours>
                <neighbour name="n3"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="s4">
            <position x="200" y="200"/>
            <neighbours>
                <neighbour name="s2"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="n1" start_time="0">
            <trainPart type="engine" speed="4"/>
            <trainPart type="cart" color="green"/>
            <trainPart type="coalWagon"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Code/szoftlab/levels/utkozes.xml
<?xml version="1.0" ?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="node1">
            <position x="1" y="0"/>
            <neighbours>
                <neighbour name="node2"/>
            </neighbours>
        </node>
        <node type="node" name="node2">
            <position x="1" y="2"/>
            <neighbours>
                <neighbour name="node1"/>
            </neighbours>
        </node>
        <node type="node" name="node3">
            <position x="0" y="1"/>
            <neighbours>
                <neighbour name="node4"/>
            </neighbours>
        </node>
        <node type="node" name="node4">
            <position x="2" y="1"/>
            <neighbours>
                <neighbour name="node3"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="node1" start_time="0">
            <trainPart type="engine"/>
        </train>
        <train start_node="node3" start_time="0">
            <trainPart type="engine"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Code/szoftlab/levels/level_2.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="n1">
            <position x="0" y="320"/>
            <neighbours>
                <neighbour name="sw1"/>
            </neighbours>
        </node>
		
        <node type="switch" name="sw1">
            <position x="80" y="300"/>
            <neighbours>
                <neighbour name="st1"/>
                <neighbour name="n2"/>
                <neighbour name="n1"/>
            </neighbours>
        </node>
		
		<node type="station" name="st1" color="green">
            <position x="120" y="250"/>
            <neighbours>
                <neighbour name="sw1"/>
				<neighbour name="sw2"/>
            </neighbours>
        </node>
		
		<node type="switch" name="sw2">
            <position x="190" y="220"/>
            <neighbours>
                <neighbour name="sw3"/>
                <neighbour name="st1"/>
                <neighbour name="n3"/>
            </neighbours>
        </node>
		
		<node type="switch" name="sw3">
            <position x="280" y="290"/>
            <neighbours>
                <neighbour name="sw2"/>
                <neighbour name="ls1"/>
                <neighbour name="sw4"/>
            </neighbours>
        </node>

		<node type="loaderStation" name="ls1" color="green">
            <position x="190" y="360"/>
            <neighbours>
                <neighbour name="sw3"/>
				<neighbour name="n2"/>
            </neighbours>
        </node>
		
        <node type="node" name="n2">
            <position x="170" y="420"/>
            <neighbours>
                <neighbour name="ls1"/>
				<neighbour name="sw1"/>
            </neighbours>
        </node>
		
		<node type="node" name="n3">
            <position x="210" y="170"/>
            <neighbours>
                <neighbour name="sw2"/>
				<neighbour name="n4"/>
            </neighbours>
        </node>
		
		<node type="node" name="n4">
            <position x="300" y="150"/>
            <neighbours>
                <neighbour name="n3"/>
				<neighbour name="n5"/>
            </neighbours>
        </node>
		
		<node type="node" name="n5">
            <position x="610" y="200"/>
            <neighbours>
                <neighbour name="n4"/>
				<neighbour name="sw5"/>
            </neighbours>
        </node>
		
		<node type="switch" name="sw4">
            <position x="400" y="300"/>
            <neighbours>
                <neighbour name="sp1"/>
                <neighbour name="ls2"/>
                <neighbour name="sw3"/>
            </neighbours>
        </node>
		
		<node type="loaderStation" name="ls2" color="blue">
            <position x="490" y="330"/>
            <neighbours>
                <neighbour name="sw4"/>
				<neighbour name="sw5"/>
            </neighbours>
        </node>
		
		<node type="switch" name="sw5">
            <position x="580" y="320"/>
            <neighbours>
                <neighbour name="ls2"/>
                <neighbour name="n5"/>
                <neighbour name="sw6"/>
            </neighbours>
        </node>
		
		<node type="specialPlace" name="sp1">
            <position x="500" y="130"/>
            <neighbours>
                <neighbour name="sw4"/>
            </neighbours>
        </node>
		
		<node type="switch" name="sw6">
            <position x="620" y="380"/>
            <neighbours>
                <neighbour name="st2"/>
                <neighbour name="sw5"/>
                <neighbour name="n6"/>
            </neighbours>
        </node>
		
		<node type="station" name="st2" color="red">
            <position x="580" y="450"/>
            <neighbours>
                <neighbour name="sw6"/>
				<neighbour name="st3"/>
            </neighbours>
        </node>
		
		<node type="station" name="st3" color="blue">
            <position x="420" y="450"/>
            <neighbours>
                <neighbour name="st2"/>
				<neighbour name="n7"/>
            </neighbours>
        </node>
		
		<node type="node" name="n7">
            <position x="320" y="430"/>
            <neighbours>
                <neighbour name="st3"/>
				<neighbour name="sp2"/>
            </neighbours>
        </node>
		
		<node type="specialPlace" name="sp2">
            <position x="310" y="350"/>
            <neighbours>
                <neighbour name="n7"/>
            </neighbours>
        </node>
		
		<node type="node" name="n6">
            <position x="800" y="500"/>
            <neighbours>
				<neighbour name="sw6"/>
            </neighbours>
        </node>
	</nodes>
	<trains>
	<train start_node="n6" start_time="200">
		<trainPart type="engine" speed="2"/>
		<trainPart type="cart" color="blue"/>
		<trainPart type="cart" color="red"/>
		<trainPart type="cart" color="blue"/>
	</train>
	<train start_node="n1" start_time="0">
		<trainPart type="engine" speed="2"/>
		<trainPart type="cart" color="green"/>
		<trainPart type="cart" color="red"/>
		<trainPart type="cart" color="red"/>
	</train>
</trains>
	
</level>

=== AdjustmentBeaver/szoftlab/Assets/levels/jatekallas_betoltes.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="node1">
            <position x="20" y="20"/>
            <neighbours>
                <neighbour name="specialPlace1"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="specialPlace1">
            <position x="80" y="20"/>
            <neighbours>
                <neighbour name="node1"/>
                <neighbour name="specialPlace2"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="specialPlace2">
            <position x="160" y="20"/>
            <neighbours>
                <neighbour name="node2"/>
                <neighbour name="specialPlace1"/>
            </neighbours>
        </node>
        <node type="node" name="node2">
            <position x="240" y="20"/>
            <neighbours>
                <neighbour name="specialPlace2"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="node1" start_time="3">
            <trainPart type="engine" speed="1"/>
        </train>
    </trains>
</level>

=== AdjustmentBeaver/szoftlab/Assets/levels/sptest.xml
<?xml version="1.0"?>
<!-- A palya formatumat leiro DTD fajl -->
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <nodes>
        <node type="node" name="n1">
            <position x="0" y="300"/>
            <neighbours>
                <neighbour name="n2"/>
            </neighbours>
        </node>
        <node type="node" name="n2">
            <position x="600" y="300"/>
            <neighbours>
                <neighbour name="n1"/>
            </neighbours>
        </node>
        <node type="node" name="n3">
            <position x="300" y="0"/>
            <neighbours>
                <neighbour name="sp1"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="sp1">
            <position x="300" y="100"/>
            <neighbours>
                <neighbour name="n3"/>
            </neighbours>
        </node>
        <node type="specialPlace" name="sp2">
            <position x="300" y="450"/>
            <neighbours>
                <neighbour name="n4"/>
            </neighbours>
        </node>
        <node type="node" name="n4">
            <position x="300" y="600"/>
            <neighbours>
                <neighbour name="sp2"/>
            </neighbours>
        </node>
    </nodes>
    <trains>
        <train start_node="n1" start_time="0">
            <trainPart type="engine" speed="2"/>
            <trainPart type="cart" color="red"/>
            <trainPart type="coalWagon"/>
        </train>
        <train start_node="n3" start_time="0">
            <trainPart type="engine" speed="2"/>
            <trainPart type="coalWagon"/>
        </train>
    </trains>
</level>
